trigger:
- main

pool:
  name: "Self-Hosted ADO Agent"

variables:
  tag: '$(Build.BuildId)'
  PROJECT_NAME: 'WebGoat-Azure'
  PROJECT_VERSION: '$(Build.SourceBranchName)-$(Build.BuildId)'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: |
        whoami
        id
        docker version
        java -version
      displayName: Env + Docker sanity

    - script: |
        chmod +x ./mvnw
        ./mvnw -v
        ./mvnw clean install
      displayName: Build WebGoat with mvnw (JDK 23 on host)

    - task: Docker@2
      displayName: Build image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: 'webgoat/webgoat'
        tags: |
          $(tag)

- stage: Security
  dependsOn: Build
  jobs:
  - job: BlackDuckSCA
    steps:
    - script: |
        java -version
        ./mvnw -v
      displayName: JDK sanity

    - script: |
        cat > bridge.yml <<'YAML'
        blackduck:
          url: ${BD_URL}
          token: ${BD_TOKEN}
          project:
            name: ${PROJECT_NAME}
            version: ${PROJECT_VERSION}
        coverity:
          connect:
            url: ${COV_URL}
            user: ${COV_USER}
            passphrase: ${COV_PASSPHRASE}
            stream: ${COV_STREAM}
          build:
            cleanCommand: ./mvnw -B -DskipTests clean
            buildCommand: ./mvnw -B -DskipTests package
        YAML
      displayName: Generate bridge.yml

    - task: BlackDuckSecurityScan@2.2.0
      displayName: 'Black Duck scan (Bridge)'
      inputs:
        bridge_installation_type: 'download'
        include_blackduck: true
        include_coverity: false
        blackduck_url: '$(BD_URL)'
        blackduck_token: '$(BD_TOKEN)'
        additional_args: >-
          --config bridge.yml
          --diagnostic
          --network.ssl.trustAll=true          # <-- trust all SSL certs (quickest)
          # or: --blackduck.trust.cert=true    # Detect-style flag that also works

  - job: Coverity
    steps:
    - script: |
        java -version
        ./mvnw -v
      displayName: JDK sanity

    - task: BlackDuckSecurityScan@2.2.0
      displayName: Coverity scan (Bridge)
      inputs:
        bridge_installation_type: 'download'
        include_blackduck: false
        include_coverity: true
        coverity_url: '$(COV_URL)'
        coverity_user: '$(COV_USER)'
        coverity_passphrase: '$(COV_PASSPHRASE)'
        additional_args: '--config bridge.yml --diagnostic'