trigger:
- main

# Use your self-hosted agent everywhere by default
pool:
  name: "Self-Hosted ADO Agent"

variables:
  tag: '$(Build.BuildId)'
  PROJECT_NAME: 'WebGoat-Azure'
  PROJECT_VERSION: '$(Build.SourceBranchName)-$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - script: |
        echo "Agent name: $AGENT_NAME"
        docker version
      displayName: Verify Docker is working

    - task: Docker@2
      displayName: Build image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: 'webgoat/webgoat'
        tags: |
          $(tag)

- stage: Security
  displayName: Security Scans
  dependsOn: Build
  jobs:

  - job: BlackDuckSCA
    displayName: Black Duck SCA (Bridge)
    steps:
    - script: |
        java -version
        mvn -v
        docker version
      displayName: Env sanity

    - task: JavaToolInstaller@0
      displayName: 'Use Temurin JDK 17'
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    - script: |
        mvn -B -DskipTests package
      displayName: 'Build with Maven'

    - script: |
        cat > bridge.yml <<'YAML'
        blackduck:
          url: ${BD_URL}
          token: ${BD_TOKEN}
          project:
            name: ${PROJECT_NAME}
            version: ${PROJECT_VERSION}
        coverity:
          connect:
            url: ${COV_URL}
            user: ${COV_USER}
            passphrase: ${COV_PASSPHRASE}
            stream: ${COV_STREAM}
          build:
            cleanCommand: mvn -B -DskipTests clean
            buildCommand: mvn -B -DskipTests package
        YAML
      displayName: 'Generate bridge.yml'

    - task: BlackDuckSecurityScan@2.2.0
      displayName: 'Black Duck scan (Bridge)'
      inputs:
        bridge_installation_type: 'download'
        include_blackduck: true
        include_coverity: false
        blackduck_url: '$(BD_URL)'
        blackduck_token: '$(BD_TOKEN)'
        additional_args: '--config bridge.yml --diagnostic'
        # To scan the built Docker image too, add:
        # additional_args: '--config bridge.yml --diagnostic --detect.tools=SIGNATURE_SCAN --detect.docker.image=webgoat/webgoat:$(tag)'

  - job: Coverity
    displayName: Coverity (Bridge Thin Client)
    steps:
    - script: |
        java -version
        mvn -v
        docker version
      displayName: Env sanity

    - task: JavaToolInstaller@0
      displayName: 'Use Temurin JDK 17'
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    - task: BlackDuckSecurityScan@2.2.0
      displayName: 'Coverity scan (Bridge)'
      inputs:
        bridge_installation_type: 'download'
        include_blackduck: false
        include_coverity: true
        coverity_url: '$(COV_URL)'
        coverity_user: '$(COV_USER)'
        coverity_passphrase: '$(COV_PASSPHRASE)'
        additional_args: '--config bridge.yml --diagnostic'
