trigger:
- main

pool:
  name: "Self-Hosted ADO Agent"

# -----------------------------
# Variables (override at queue time if you like)
# -----------------------------
variables:
- name: tag
  value: '$(Build.BuildId)'
- name: PROJECT_NAME
  value: 'WebGoat-Azure'
- name: PROJECT_VERSION
  value: '$(Build.SourceBranchName)-$(Build.BuildId)'
- name: COVERITY_PROJECT_NAME
  value: '$(Build.Repository.Name)'
- name: COVERITY_STREAM_NAME
  value: '$(Build.SourceBranchName)'
# Secrets expected in pipeline/variable group:
#   BD_URL, BD_TOKEN
#   COV_URL (e.g., https://coverity.mycorp.local:8443), COV_USER, COV_PASSPHRASE

stages:

# =====================
# 1) Build from source
# =====================
- stage: Build
  displayName: Build WebGoat + image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - script: |
        echo "== Env sanity =="
        whoami
        id
        docker version || true
        java -version || true
      displayName: Env + Docker + JDK sanity

    - script: |
        chmod +x ./mvnw
        ./mvnw -v
        ./mvnw -B clean install
      displayName: Build WebGoat with mvnw (produces target/webgoat-*.jar)

    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: 'webgoat/webgoat'
        tags: |
          $(tag)

# =========================
# 2) Security scans (Bridge)
# =========================
- stage: Security
  displayName: Security Scans
  dependsOn: Build
  jobs:

  # ---- Black Duck SCA (Bridge) ----
  - job: BlackDuckSCA
    displayName: Black Duck SCA (Bridge)
    steps:
      - script: |
          java -version || true
          ./mvnw -v
        displayName: JDK sanity

      - task: BlackDuckSecurityScan@2
        displayName: Black Duck SCA Scan (Bridge)
        env:
          DETECT_PROJECT_NAME: $(PROJECT_NAME)
          DETECT_PROJECT_VERSION_NAME: $(PROJECT_VERSION)
          DETECT_SELF_UPDATE_DISABLED: "true"
        inputs:
          blackducksca_url: $(BD_URL)
          blackducksca_token: $(BD_TOKEN)
          # Nice-to-haves from the working sample:
          blackducksca_scan_failure_severities: 'BLOCKER'
          blackducksca_fixpr_enabled: true
          blackducksca_prcomment_enabled: true
          blackducksca_reports_sarif_create: true
          azure_token: $(System.AccessToken)
          mark_build_status: 'SucceededWithIssues'
          # Temporary only; prefer installing the CA instead:
          # network_ssl_trust_all: true

  # ---- Coverity (Bridge thin client) ----
  - job: Coverity
    displayName: Coverity (Bridge)
    steps:
      - script: |
          java -version || true
          ./mvnw -v
        displayName: JDK sanity

      # Sanitize names (kept as-is)
      - bash: |
          set -euo pipefail
          PROJ_RAW='$(COVERITY_PROJECT_NAME)'
          STRM_RAW='$(COVERITY_STREAM_NAME)'
          sanitize () { echo "$1" | tr '/ ' '--' | sed -E 's/[^A-Za-z0-9._-]/-/g' | cut -c1-200; }
          PROJ_CLEAN="$(sanitize "$PROJ_RAW")"
          STRM_CLEAN="$(sanitize "$STRM_RAW")"
          echo "Coverity Project (raw -> clean): $PROJ_RAW -> $PROJ_CLEAN"
          echo "Coverity Stream  (raw -> clean): $STRM_RAW -> $STRM_CLEAN"
          echo "##vso[task.setvariable variable=COVERITY_PROJECT_NAME]$PROJ_CLEAN"
          echo "##vso[task.setvariable variable=COVERITY_STREAM_NAME]$STRM_CLEAN"
        displayName: Sanitize Coverity project/stream names

      # Connectivity check that respects your scheme in COV_URL
      - bash: |
          set -euo pipefail
          echo "Agent egress IP:"; (curl -s https://ifconfig.me || curl -s https://api.ipify.org); echo
          URL="$(echo '$(COV_URL)' | sed 's#/*$##')"
          HOST="$(echo "$URL" | sed -E 's@^https?://([^:/]+).*$@\1@')"
          PORT="$(echo "$URL" | sed -nE 's@^https?://[^:/]+:([0-9]+).*@\1@p')"
          SCHEME="$(echo "$URL" | sed -E 's@^(https?)://.*@\1@')"
          [ -z "$PORT" ] && PORT=$([ "$SCHEME" = https ] && echo 8443 || echo 8080)
          echo "Testing $SCHEME to $HOST:$PORT ..."
          # Try the tools list endpoint Bridge calls during connect
          if ! curl -fsS -m 10 "$SCHEME://$HOST:$PORT/api/v2/scans/toolslist" >/dev/null; then
            echo "ERROR: Cannot reach $SCHEME://$HOST:$PORT from this agent."
            echo "       Open the firewall/SG to this agent IP or move the agent inside the network."
            exit 86
          fi
          echo "OK: $SCHEME://$HOST:$PORT is reachable."
        displayName: Connectivity check to Coverity

      - task: BlackDuckSecurityScan@2
        displayName: Coverity Scan (Bridge thin client)
        env:
          COVERITY_PROJECT_NAME: $(COVERITY_PROJECT_NAME)
          COVERITY_STREAM_NAME:  $(COVERITY_STREAM_NAME)
        inputs:
          coverity_url: $(COV_URL)
          coverity_user: $(COV_USER)
          coverity_passphrase: $(COV_PASSPHRASE)
          coverity_prcomment_enabled: true
          azure_token: $(System.AccessToken)
          mark_build_status: 'SucceededWithIssues'
          # Temporary only; prefer installing the CA instead:
          # network_ssl_trust_all: true
          # If you *must* do local analysis, uncomment these two (prefer a writable temp dir):
          # coverity_local: true
          # coverity_install_directory: $(Agent.TempDirectory)/cov-platform

      # Optional: zip and publish Bridge logs (disabled by default)
      - task: ArchiveFiles@2
        displayName: 'Copy Bridge Logs'
        condition: succeededOrFailed()
        enabled: false
        inputs:
          rootFolderOrFile: .bridge
          includeRootFolder: false
          archiveFile: '$(Build.ArtifactStagingDirectory)/bridge-logs.zip'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Bridge Logs'
        condition: succeededOrFailed()
        enabled: false
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'logs'
